name: npm-publish
on:
  workflow_dispatch:
  push:
    branches:    
      - 'main'
      - 'master'
    tags:        
      - v[0-9]+.[0-9]+.[0-9]+
    paths:
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
